name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use_cross: false
          
          # Linux i386
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use_cross: true

          # Linux ARM64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use_cross: true

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Check formatting
      run: cargo fmt --all --check

    - name: Install Cross
      if: matrix.use_cross
      run: cargo install cross --git https://github.com/cross-rs/cross

    - name: Build rtimage
      working-directory: rtimage
      run: |
        if [ "${{ matrix.use_cross }}" = "true" ]; then
          cross build --verbose --target ${{ matrix.target }}
        else
          cargo build --verbose --target ${{ matrix.target }}
        fi

    - name: Build rtinfo
      working-directory: rtinfo
      run: |
        if [ "${{ matrix.use_cross }}" = "true" ]; then
          cross build --verbose --target ${{ matrix.target }}
        else
          cargo build --verbose --target ${{ matrix.target }}
        fi

    - name: Run tests rtimage
      working-directory: rtimage
      run: |
        if [ "${{ matrix.use_cross }}" = "true" ]; then
          cross test --verbose --target ${{ matrix.target }}
        else
          cargo test --verbose --target ${{ matrix.target }}
        fi

    - name: Run tests rtinfo
      working-directory: rtinfo
      run: |
        if [ "${{ matrix.use_cross }}" = "true" ]; then
          cross test --verbose --target ${{ matrix.target }}
        else
          cargo test --verbose --target ${{ matrix.target }}
        fi
